include: package:lint/analysis_options.yaml

analyzer: 
  errors:
    library_names: error
    file_names: error
    prefer_final_locals: error
    unused_import: warning
    always_declare_return_types: error
    avoid_positional_boolean_parameters: error
    unnecessary_null_checks: error
    unnecessary_new: error
    avoid_print: warning
    leading_newlines_in_multiline_strings: error
    unnecessary_this: error
    avoid_function_literals_in_foreach_calls: error
    avoid_unnecessary_containers: error
    avoid_redundant_argument_values: error
    directives_ordering: error
    unnecessary_string_interpolations: error
    prefer_is_empty: error
    unnecessary_await_in_return: error
    unused_local_variable: warning
    must_be_immutable: ignore
    noop_primitive_operations: error
    unused_field: warning
    prefer_final_fields: error
    unused_element: warning
    unnecessary_breaks: error

linter:
  rules:
    sort_pub_dependencies: false
    prefer_const_constructors_in_immutables: false
    library_prefixes: false
    avoid_bool_literals_in_conditional_expressions: false
    prefer_const_constructors: false
    avoid_redundant_argument_values: false
    parameter_assignments: false
    avoid_classes_with_only_static_members: false
    prefer_initializing_formals: false
    require_trailing_commas: false
    use_build_context_synchronously: false
    cast_nullable_to_non_nullable: false
